version = 0.1

[dev.deploy.parameters]
region = "ap-northeast-1"
stack_name = "sam-deploy-stack"
s3_bucket = ""
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Env=xxxx",
    "Prefix=xxxx"
]
